version: "3.9"

services:
  wall_e:

    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: wall_e

    network_mode: host
    ipc: host

    privileged: true

    stdin_open: true
    tty: true

    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}

    volumes:
      # Workspace ROS
      - ./ros2_ws:/workspace/ros2_ws

      # X11 (RViz, rqt...)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      # Caméras USB
      - /dev:/dev

    working_dir: /workspace/ros2_ws

    command: bash
  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

